### ISSUE TITLE
[OTHER] How to Contribute to the Frontend of Taipy

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Avaiga/taipy#1319]
### What would you like to share or ask?

Hi team,

I was wondering if there is a way to contribute to the frontend of Taipy. I'm good with Next.js and React, but I wasn't able to run it locally even after following the instructions in the README (Taipy-GUI and Taipy frontend).

Do you accept contributions in that part, such as optimization of the existing Taipy website?

Thanks!

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
You can take any issue with ["good first issue"](https://github.com/Avaiga/taipy/labels/good%20first%20issue) or ["Help wanted"](https://github.com/Avaiga/taipy/labels/%F0%9F%86%98%20Help%20wanted) labels.

This list includes several issues related to the GUI that might interest you. Contributing to the website part seems difficult.

Could you describe what error you got when you ran locally so that we can help you?

**Comment by FlorianJacta** [comment]
@Anmol-Baranwal, do you have any updates on this?

**Comment by Anmol-Baranwal** [comment]
@FlorianJacta 
Thank you!
I missed the notification somehow, I understand the codebase structure better now so I'm closing this issue. I will make sure to pick up good first issues related to the GUI.

**Comment by FlorianJacta** [comment]
Great! We are here to help if you need anything
