### ISSUE TITLE
Docs for "Progress" visual element are missing

### ISSUE THREAD

**Issue by yaten2302** [Avaiga/taipy#1464]
### Issue Description

The docs for a newly created Progress element are missing, here's the PR for the vis element - https://github.com/Avaiga/taipy/pull/1303

### Proposed Solution (optional)

On taipy.io, we can add a the docs for progress element.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by jrobinAV** [comment]
Hi @yaten2302 

Let us add more details on how to add documentation so you can start working on it.

Thanks a lot

**Comment by yaten2302** [comment]
Hey @jrobinAV , yes sure, I would definitely work on this issue 👍 Actually, I've only implemented the  `Progress` element, so I'm quite familiar with it. Could, you please give some info on how can I get started with it and then I'll implement this in the website.

BTW, it has to be similar to [this](https://docs.taipy.io/en/latest/manuals/gui/viselements/button/), right?

**Comment by FabienLelaquais** [comment]
Hi @yaten2302 and thank you for your help on this one!
And yes, using [the documentation for button](https://docs.taipy.io/en/develop/manuals/userman/gui/viselements/generic/button) is a great start.

The very first thing you must do is insure you can build the Taipy documentation locally. The (short) file [`[taipy-doc]/INSTALLATION.md`](https://github.com/Avaiga/taipy-doc/blob/develop/INSTALLATION.md) should give all the information you need.

You have to know a few things about unsaid rules on documenting visual elements before you start.
- Documenting a visual element has impacts on both [`taipy`](https://github.com/Avaiga/taipy) rand [`taipy-doc`](https://github.com/Avaiga/taipy-doc)  repositories.
- The documentation mainly sits in the [`taipy-doc`](https://github.com/Avaiga/taipy-doc) repository.
   - [This issue](https://github.com/Avaiga/taipy-doc/issues/1056) captures the `taipy-doc` side of the work for this case.
   - The main element doc page is generated by merging a template file located in `*taipy-doc*/docs/manuals/userman/gui/viselements/generic/<element_type>.md_template` and the description file `*taipy*/taipy/gui/viselements.json`.
   - The doc template file has three main sections that must be filled in:
      - An introduction section where the first line is used as a short description in [the elements palette](https://docs.taipy.io/en/develop/manuals/userman/gui/viselements/) page.
      - A 'Details' section where deeper explanations are needed for some properties (besides what is described in `viselements.json`) 
      - A 'Usage' section that presents tiny independent examples addressing an identified use case.
         - Every example must contain at least the definition of the documented control for this case (potentially using specific Python code).
         - The control definition appears in a *mkdocs* Code block that presents the definition so that it can be copied and pasted for the Markdown, HTML and Page Build API cases. Note that there is the `!!! taipy-element` shortcut syntax that generates the three cases automatically, when possible. I can provide details on that if needed.
         - The final rendering must be shown in a PNG images pair (both light and dark reading modes).

 - The [`taipy`](https://github.com/Avaiga/taipy) side is about exposing `viselements.json` (whose doc fragments must contain raw HTML - or even better, XHTML - and *not* Markdown), and code examples source files, which are stored in `[taipy]/doc/gui/examples/controls`.
     - Every example must be stored in a script called `<element_type>-<tiny_description>.py`.
     - The example must run independently when Taipy is installed (`python run <element_type>-<tiny_description>.py`)
     - If must not depend on external resources (except in exceptional cases where datasets must be fetched)
     These examples must be as simple as possible and show the impact of setting some properties to certain values.

Please get inspiration from an existing control (such as `button`) and do not hesitate to ask for help. This is the first time a contributor has participated in adding documentation to visual elements.

**Comment by yaten2302** [comment]
Thanks for your help @FabienLelaquais 👍 
So, what I've understood is that - first I've to set up the `taipy-doc` repo and make changes in this file - `*taipy-doc*/docs/manuals/userman/gui/viselements/generic/progress.md_template`?

I've a doubt, as you told that the progress element has to be added in here as well `*taipy*/taipy/gui/viselements.json`, but the `progress` is already present [here](https://github.com/Avaiga/taipy/blob/develop/taipy/gui/viselements.json#L1260).

And yes, for the doc template file, I've understood about it 👍 

For, the main `taipy` repo, I've a doubt that as you told that there should be and example present in this dir - `[taipy]/doc/gui/examples/controls` for the ease of the developer, so in this issue, can the example be like - creating a simple progress element by showing both the linear and circular progress bars? And yes, I'll make sure that there are no external resources 👍

**Comment by FabienLelaquais** [comment]
> you told that the progress element has to be added in here as well

You got my point exactly.
You should come up with a few, very simple examples that demonstrate how properties impact the rendering and/or the ability for a user to act on a control.
So usually we start with a 'simple' example (in a file stored at `[taipy]/doc/gui/examples/controls/progress-simple.py`), where you will certainly set a relevant value for the *value* property and you're done. No other property.
A second example (in a file stored at `[taipy]/doc/gui/examples/controls\progress-linear.py`) would be to show a linear progress bar by just setting the *linear* property to True.
Finally you may want to show how to hide the value itself (using the `show_value` property).
And you're done.

If you have any problem generating the images, don't hesitate to leave that to me. I'll be happy to take screen shots as needed.

Thanks again.

Note that I never said "that the progress element has to be added in [...]viselements.json".
It is part of the development task, when we provide a simple documentation of the element properties.
May be I did that, I don't remember to be honest.
So yes it exists, and part of the job is making sure this simple doc is accurate and complete.
I did spot a 'TODO' in there (that I certainly added) that needs a resolution.

**Comment by yaten2302** [comment]
@FabienLelaquais , thank you so much for the clear explanation. Now, I'm very much clear with what and how I've to proceed. I'll resolve this issue ASAP 👍 

I'm really happy that I'm a contributor at  Taipy and would definitely like to become a member of the Taipy famly someday 😄

**Comment by FabienLelaquais** [comment]
I sincerely hope this can happen some day, @yaten2302. Your input is very valuable.
Thank you.

**Comment by yaten2302** [comment]
Hey @FabienLelaquais , actually, I was trying to display the code for the markdown, html and python for the progress, but, I'm facing an issue, that when I'm doing changing the `progress.md_template` and `progress.md` files, these changes are being shown,  could you please guide where I'm making the mistake? <br>
![image](https://github.com/user-attachments/assets/806bda23-3c93-40b5-8a0c-ba4fad6ee3ba)

**Comment by yaten2302** [comment]
Like, I'm not able to see in this format <br>
![image](https://github.com/user-attachments/assets/4a84a1ff-123b-4dcd-9a9f-d8587abe67e8)

**Comment by yaten2302** [comment]
BTW, I also wanted to ask that, the `.md` files, like `button.md` are in the `.gitignore`, so any changes made in those will not be displayed right?

**Comment by yaten2302** [comment]
Also, I've linked a [PR](https://github.com/Avaiga/taipy-doc/pull/1060) to this issue, this PR is not complete, it's just the beginning of the docs work and I'll keep adding my progress in this PR 👍

**Comment by FabienLelaquais** [comment]
Oh. The thing you are missing is the doc build process described in ` [taipy-doc]/INSTALLATION.md` .
Here is how it goes (pay close attention to step 2, which you are missing):
- 1 First, you must copy the product source files locally, so that the Reference Manual can be generated.
  This is done by invoking, from the ` taipy-doc` root directory: `python tools/fetch_source_files.py develop`.
   This copies all mandatory files locally, from the ` develop` branch of the relevant GitHub repositories.
   Il also computes a merged Pipfile so all dependencies can be resolved when parsing the source files.
   So you will need to: `pipenv install --dev`.
   This operation can be done once and for all, as long as source files don' t change, or if you don't really care at this point.
-  2 Then you must setup all files before you run ` mkdocs`.
   From the ` taipy-doc` root directory, run `pipenv run python tools/setup_generation.py`.
   This will generate all the files that ` mkdocs` relies on.
   That includes Markdown files for the Reference Manual, as well as fill in the template files (such as the ` .md_template` files you need to modify).
- 3 Finally, you can see your generated doc: ` pipenv run mkdocs serve`.

Now for your questions:
- " I'm doing changing the progress.md_template and progress.md files" you should not do that.
  Only the md_template file should be modified, then the related md file would be generated by the setup_generation script.
- ".md files, like button.md are in the .gitignore": yes. That's because these are generated (by `setup_generation.py`).
   All *_template files are processed by this script, and generate the final file next to it.
   In our example, ` progress.md_template` is processed to generate `progress.md` will all the control properties automatically sneaking in.

Your example lacks the mandatory use of the *value* property.

Does that makes sense?

**Comment by yaten2302** [comment]
@FabienLelaquais , I followed all the steps exactly, as you mentioned here(which are the same as in the INSTALLSTION.md), except the last one! I did - `mkdocs serve` instead of `pipenv run mkdocs serve`, actually, in the installation.md, it was mentioned `mkdocs serve`, so that's why did.

And, yes, in my example, the `value` param is missing right now, I'll add it, this PR was just for showing the changes, which I've made till now, this is not the final PR.

**Comment by yaten2302** [comment]
@FabienLelaquais , I just figured out that where I was making the mistake. I've added the html/markdown/python code in the md_template file itself, rather than adding it in this dir - `[taipy]/doc/gui/examples/controls\progress-linear.py` (as you told in your previous comment).

But, I've a doubt, that when I'll add this, then it'll be in a different repo, so after that, do I've to run the steps in installation.md again? after that my changes will be reflected or it's something else?

**Comment by FabienLelaquais** [comment]
@yaten2302 
Adding the examples in the `taipy` repo has no impact on the doc generation: we just create a link from the doc to the GitHub location. No worries about that.
The rules are:
- You must re-run the *fetch* command (step 1) if and only if the taipy code has changed (source files) or the `viselements.json` file.
- You must re-run the *setup* command (step 2) if and only if *fetch* was performed, or when any *template* file (such as those `md_template` file) is modified.

What I do actually is: in the taipy-doc repo, I update my *.md file (and NOT the template file) until I'm happy with the result.
When I'm done, I compare the md file with the md_template file, and update the template file with all I've done, expect for the code that is generated (like the element's properties section and the elements definition - the !!!taipy-element thing).
When I work on an element's documentation, that process saves a lot of time since I don't have to regenerate the md file over and over when I change a word to another.

Please let me know if this makes things more clear.

Note: I will fix the error in the INSTALLATION.md file. Thanks.

**Comment by yaten2302** [comment]
@FabienLelaquais , actually, I was trying to create the code for the "value" param as well, but when I added a new 
```
!!! taipy-element
        value=50
        default=True
```

then both the code got changed, could you please guide <br>
![image](https://github.com/user-attachments/assets/351a0538-fa95-431e-89dd-4e0319849242)

Like, before adding the 2nd `!!! taipy-element`, it was working fine, but after adding this, this occurred <br>
![image](https://github.com/user-attachments/assets/459a68b3-d806-4a22-98f2-f14ff227075f)

**Comment by FabienLelaquais** [comment]
So you have two problems here:
- The first one is due to no documentation on this !!! taipy-element thing.
  The syntax is (a bit simplified):
    ```
     !!! taipy-element
         <property-name1>=<value>
         <property-name2>=<value>
         ...
    ```
    There is one exception: the default property.
     In your case, that is 'value'.
     So basically,
     ```
      !!! taipy-element
         default=10
         render=True
         ...
     ```
    is kind of equivalent to
     ```
      !!! taipy-element
         value=10
         render=True
         ...
     ```
    except that then, the default property is never used.
    In the first case Markdown, that would generate: `<|10|progress|render=True|>` which is fine.
    The second case would generate: `<|progress|value=10|render=True|>`. Although equivalent, we favor the first.
    
- The second problem is simply due to the fact that you don't have a carriage return at the end of your file.
   Just add a new line, you're good to go.

**Comment by yaten2302** [comment]
Hey @FabienLelaquais , sorry for the huge delay. Actually, I've closed the previous PR (there was some issue in that) I'll create a new one with the changes 🙏

**Comment by FabienLelaquais** [comment]
I'll be watching. Don't worry @yaten2302. Sometimes things get messy.
Cheers

**Comment by yaten2302** [comment]
Hey @FabienLelaquais , I've made the changes, it's working perfectly fine now 🎉 <br>
![image](https://github.com/user-attachments/assets/3dcd282b-afcd-4965-8f18-4815d2310f57)

Now, I'm adding for the `linear=True` param and then ig we're good to go?

**Comment by yaten2302** [comment]
@FabienLelaquais , is this looking good? <br>
![image](https://github.com/user-attachments/assets/df7333eb-bb00-476e-85ee-aca6ec352ca0)

**Comment by yaten2302** [comment]
@FabienLelaquais , I've created a PR, could you please review that and LMK if any changes are required in it 👍

**Comment by FabienLelaquais** [comment]
Thank you @yaten2302. Looking good indeed.
I'll look at that really soon.
