### ISSUE TITLE
Store favicon traffic metrics

### ISSUE THREAD

**Issue by florian-vuillemot** [Avaiga/taipy#1466]
### Description

Taipy now uses a favicon saved on [GitHub](https://github.com/Avaiga/taipy-assets). GitHub keeps traffic data for 14 days, and we would like to keep this data for longer.

We are already persisting the taipy repository traffic every day with Azure Data Factory. We must update our ADF to do the same with the taipy-asset repository.

### Acceptance Criteria

- [ ] The traffic must be saved every day.
- [ ] Ensure any change is well documented.

**Comment by sOnU1002** [comment]
i would liketo work on the issue sir please assign this to me

**Comment by FlorianJacta** [comment]
@sOnU1002 This is not an issue for Hacktoberfest

**Comment by jrobinAV** [comment]
@sOnU1002 Sorry for the inconvenience, but this issue is for staff only. 
You will not be able to complete it as it requires some access to private resources. 

Don't hesitate to look at our issues open for contribution [here](https://github.com/Avaiga/taipy/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22%2C%22%F0%9F%86%98+Help+wanted%22+),
and in particular, the ones for Hacktoberfest.
