### ISSUE TITLE
[DOCS] editable__columnname is not documented

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1621]
### Issue Description

The proper syntax to make the "Demand" column of a table editable in tgb is:
```python
tgb.table("{demand_table}", on_edit=edit_demand, editable__Demand=True)
```
But this syntax is not documented in the docs:
https://docs.taipy.io/en/develop/manuals/userman/gui/viselements/generic/table/
https://docs.taipy.io/en/develop/tutorials/visuals/2_using_tables/

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FabienLelaquais** [comment]
The title of this issue should be something like "Index properties are not documented in the Page Builder API".

The thing is... we have no satisfactory response just yet. The syntax you mention does work, but may not in the future.
The reason is that column names (or datasets, in the case of charts) may to be valid Python indentifiers.
Anyway... that is relevant. Thanks.

**Comment by Shivam250702** [comment]
Hi @AlexandreSajus , I would like to work on this issue, please assign this issue to me

**Comment by FabienLelaquais** [comment]
Thank you for your proposal @Shivam250702.
The truth is we have done it in the develop branch for the doc already, in a rush to ship the best possible doc.
You are welcome to check `https://docs.taipy.io/en/develop/userman/gui/pages/builder/#setting-property-values` and comment in this issue if you think this should have be done better.
Thanks
(@AlexandreSajus, for information)

**Comment by AlexandreSajus** [comment]
https://docs.taipy.io/en/develop/userman/gui/pages/builder/#setting-property-values
Closed
