### ISSUE TITLE
Scenario Selector - Handle "Delete" of primary scenarios

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#166]
## Issue

It is possible to click on the button to delete a primary scenario. This will raise an error and show a string below the visual element.

`Error deleting Scenario. Scenario SCENARIO_scenario_46baaf71-5290-4d8d-99db-05fb54614482, which has config id scenario, is primary and there are other scenarios in the same cycle.
`

## Expected behaviour

It should not be possible to delete primary scenarios in Scenario Selector.

## Version
Taipy: 2.3.0 Draft

**Comment by jrobinAV** [comment]
A scenario can be deleted if and only if 
(it is not primary) or (it is the only scenario of its cycle).
Otherwise, the deletion raises an error. 

We probably want to implement the same rule in the Scenario selector. The business logic should remain in `taipy-core`. Maybe an API should be opened on `taipy-core` (`is_scenario_deletable`) that returns true if the scenario can be deleted.

I drop the code that deletes the scenario here, so the rule is understandable:
```python
def _delete(cls, scenario_id: ScenarioId):
        scenario = cls._get(scenario_id)
        if scenario.is_primary:
            if len(cls._get_all_by_cycle(scenario.cycle)) > 1:
                raise DeletingPrimaryScenario(
                    f"Scenario {scenario.id}, which has config id {scenario.config_id}, is primary and there are "
                    f"other scenarios in the same cycle. "
                )
            _CycleManagerFactory._build_manager()._hard_delete(scenario.cycle.id)
            return
        entity_ids_to_delete = cls._get_children_entity_ids(scenario)
        entity_ids_to_delete.scenario_ids.add(scenario.id)
        cls._delete_entities_of_multiple_types(entity_ids_to_delete)
        return

```
