### ISSUE TITLE
Setting type to "none" for metrics is not UX friendly

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#2143]
### Description

The goal would be to be able to add `None`, the None Python object, to this property, as it is more user-friendly for Taipy developers using TGB.

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

value = 50 

with tgb.Page() as page:
    tgb.metric("{value}", type="none")

Gui(page=page).run(title="Frontend Demo")
```

A new and similar syntax would be:

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

value = 50 

with tgb.Page() as page:
    tgb.metric("{value}", type=None)

Gui(page=page).run(title="Frontend Demo")
``` 

### Acceptance Criteria

- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by codingis4noobs2** [comment]
Hi @FlorianJacta , I would like to work on this issue

**Comment by FredLL-Avaiga** [comment]
https://github.com/Avaiga/taipy/blob/8379661f1380a7722f1643b1252f62df55b5df8d/frontend/taipy-gui/src/components/Taipy/Metric.tsx#L90

Add support for null (None in the backend)

**Comment by AtharvChanana** [comment]
Hi @FlorianJacta , I would like to work on this issue.

**Comment by Sourav-8401** [comment]
Hey I have checked the existing issue, I am willing to work on it. can you assign this issue to me. @FlorianJacta

**Comment by aadharbata** [comment]
hey @FlorianJacta can u pls assign this task to me

**Comment by hustler0109** [comment]
Hello @FlorianJacta ,

To improve UX, I propose allowing type=None in tgb.metric() instead of "none", making it more intuitive for Python users. Here’s the plan:

Update tgb.metric() to accept type=None as an alternative to "none", ensuring backward compatibility.
Implement unit tests for both type=None and type="none", meeting the 90% coverage requirement.
This approach aligns with Python conventions and enhances usability.
I have checked the existing issues. Let me know if I can move forward with this!

Thank you!

**Comment by kris2005mehra** [comment]
Hey @FlorianJacta could you assign this task to me ? I can solve this one out
