### ISSUE TITLE
Release Taipy on Conda

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#40]
Step 0: 
We need to add to the release process the deployment of taipy on Conda.

- [x] Taipy
- [x] Taipy-core
- [x] Taipy-gui
- [x] Taipy-rest

First step: Deploy manually based on the [documentation](https://docs.google.com/document/d/1K7in6dNLmu5DkbvmCs0TwqgLkaA90Uh5Mp0xd4BJPPI/edit#heading=h.c1bzc654zbaf).

Second step: Start working on a proposal for automation.

**Comment by toan-quach** [comment]
Some notes: 
- Building the package from pip instead of from github (easier in my opinion), conda skeleton will go to pypi to extract the information of the packages, build the meta.yaml file automatically, we only have to fill in some information such as License file and homepage url.
- The package will be published under a specific channel (namely the user's channel, could be Avaiga for example), it's still public but it won't be on the default channel of anaconda (this is for well-known packages apparently). Another channel option would be conda-forge, which is also well-known and free.
- When building the packages to be published, dependencies must be declared, conda will check for the package availability on anaconda site, this posts some problem as some dependencies we are using are not available on anaconda (simple-websocket is an example). To solve this, we can publish the package on anaconda ourselves (which is quite a straight-forward process but we will need to update it ourselve)

I have published taipy-core and taipy-rest to my account as an example, you can find them here:
https://anaconda.org/toanquachp/taipy-core
https://anaconda.org/toanquachp/taipy-rest

**Comment by toan-quach** [comment]
Discussion on the topic:

- The current issue with publishing Taipy to Anaconda: dependencies not available on Anaconda entirely or the version of the dependencies doesn't meet our requirement.
- If we push the publication of Taipy on Anaconda, we will be limiting our choices of dependencies and their versioning since we have to make sure the dependency is available on Anaconda, which has lesser packages compared to Pypi and slower in updating their versioning (as observed so far) so the package will not be up-to-date compared to Pypi. 
- But if we ignore this issue and postpone the publication of Taipy on Anaconda, when we have further developed Taipy and our dependencies grow bigger, the same problem might appear for many more of our dependencies (currently we have only 2 - simple-websocket and flask-talisman). 

**Conclusion**: since we can install Pypi packages in Anaconda environment, we will postpone this for now to prioritize the freedom in choosing dependencies

**Comment by jrobinAV** [comment]
OK
So in the end, this ticket is about documentation only.
We just want to add a section in the doc to explain how to install both pip then taipy on conda.
A new subsection dedicated to installation on the Home page could be the right place.
