### ISSUE TITLE
Improve Scenario Management template

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#424]
- we could put margin to 0 in the run to make it nicer looking:
`gui.run(title="{{cookiecutter.__application_title}}", margin="0em")`

![image](https://github.com/Avaiga/taipy-templates/assets/98709993/d8da711d-598a-4066-a5bf-40cea7cb2243)

- we can delete the lines concerning the issue on `from ... import *`

- we could also use `on_submission_change` callback

**Comment by trgiangdo** [comment]
The `from ... import *` on the default template is actually necessary because when the user add a new function to the `algorithms.py` or new config to the `config.py`, it will be automatically import to the main application.

If remove those, the user will need to import the methods and config by himself.
