### ISSUE TITLE
Generalize default_data attribute for all predefined data nodes

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#535]
Today, a default data attribute in Data Node config is implemented for csv, excel, in memory, json, parquet, pickle storage types.
We want to make it generic for all data node types, in a similar way.

- [ ] Implement the data writing with default data when creating the data node for the first time.
- [ ] Unit tests
- [ ] Release notes
- [ ] User manual

**Comment by ashutuptiwari** [comment]
Is this issue still active? @jrobinAV

**Comment by jrobinAV** [comment]
Yes, absolutely.

**Comment by ashutuptiwari** [comment]
Please explain the issue in greater detail. @jrobinAV

**Comment by trgiangdo** [comment]
When configure csv, excel, in memory, json, parquet, pickle data node, you can provide the "default_data" attribute that will be automatically written to the data node if the data node does not exist yet.

The purpose of the issue is to implement the same behavior for other existing data node types.

**Comment by FlorianJacta** [comment]
This generalization seems to be strange to me. We cannot use `pd.DataFrame` in *default_data*. I would suggest them to use the *write* function instead

**Comment by jrobinAV** [comment]
@FlorianJacta I understand. Thx for your feedback.
