### ISSUE TITLE
Do not notify "Upload succesful" when uploading a file using file_selector

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#573]
A user on [Stack Overflow](https://stackoverflow.com/questions/77609658/file-selector-does-not-function-as-expected/77612365?noredirect=1#comment136833830_77612365) reported that since he only uses the file selector to get the file path, he does not want an "Uploaded successfully" notification.

**Expected change:**
The file selector should not by default send a notification when uploading a file

**Comment by DeepSkyWonder** [comment]
Can this be added to 3.1? It looks like it is only available in 4.0.  :-)

**Comment by FlorianJacta** [comment]
Did you have any issues going to the 4.0?

**Comment by DeepSkyWonder** [comment]
Hi Florian

We are currently running on 3.1.1 Community Edition, TaiPy 4.0 introduces
many changes, some of which are fantastic (metric, progress, and chat
controls, LOV's from enums, width prop. on visual elements), and some of
which are potential breaking changes (e.g. features being removed from the Community
Edition, changes to how workers behave in standalone mode, etc...)

It has only been two weeks since 4.0 was released, and normally we would
take longer to migrate to a newer version, to give ourselves the
opportunity to fully identify all the potential issues before moving it
onto our live system.

Out of the box, on our development server, we saw these issues with 4.0 relative to 3.1.1....

(1) <center> tags stopped working in markdown. This killed our UI as we
used <center> like this everywhere

Warning 1: Missing leading pipe '|' in opening tag line 10:
'<center><|{current_dateTime}|text|propagate=True|></center>'.

(2) Still tracking this one down. The markdown is
this <|{message}|text|mode=md|> and the python code is this message = '' and this in build_message
state.message = scenario.message.read()

/usr/local/lib/python3.10/site-packages/taipy/gui/gui.py:698:
TaipyGuiWarning: Decoding Message has failed: {'type': 'ID', 'name':
'TaipyClientId', 'payload': '20240907113701950055-0.1811197125785058',
'propagate': False, 'client_id': '20240907113701950055-0.1811197125785058',
'ack_id': '48001a61-4bdf-4536-83a8-49825ebccf4a', 'module_context': ''}:
hasattr(): attribute name must be string
  _warn(f"Decoding Message has failed: {message}", e)

(3) And this surprise which took down our development
server and a cluster of worker nodes. It appears to be a side effect of the new standalone mode
behaviour, interacting with our codebase.

 Process SpawnProcess-1:
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314,
in _bootstrap
     self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in
run
     self._target(*self._args, **self._kwargs)
   File "/usr/local/lib/python3.10/concurrent/futures/process.py", line
240, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 122, in
get
     return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'build_message' on <module
'__mp_main__' from '/app/main.py'>
ERROR:concurrent.futures:exception calling callback for <Future at
0x7fed89bacee0 state=finished raised BrokenProcessPool>
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 342,
in _invoke_callbacks
     callback(self)
   File
"/usr/local/lib/python3.10/site-packages/taipy/core/_orchestrator/_dispatcher/_standalone_job_dispatcher.py",
line 70, in _update_job_status_from_future
    self._update_job_status(job, ft.result())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451,
in result
    return self.__get_result()
   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403,
in __get_result
     raise self._exception
 concurrent.futures.process.BrokenProcessPool: A process in the process
pool was terminated abruptly while the future was running or pending.

Python config code

    input_name_data_node_cfg = Config.configure_data_node(id="input_name")
    message_data_node_cfg = Config.configure_data_node(id="message")
    build_msg_task_cfg = Config.configure_task("build_msg", build_message,
input_name_data_node_cfg, message_data_node_cfg)
    scenario_cfg = Config.configure_scenario("scenario",
task_configs=[build_msg_task_cfg])
    Config.configure_job_executions(mode="standalone", max_nb_of_workers=8)

Some of these could be artifacts of our development setup (e.g. (3)).
For now, we are staying with 3.1.1 until we have more confidence with
4.0. Is it possible to backport the 'do not notify' feature for file uploads
to 3.1.1? I have attached a screenshot of what the notify message looks like.
You will see why we want to disable it.

Kind Regards and thanks for this amazing software.

Cameron :-)

**Comment by DeepSkyWonder** [comment]
![Screen Shot 2024-10-22 at 10 44 17 AM](https://github.com/user-attachments/assets/8f503ce5-0fa1-42b6-8a4c-41967af2b71b)

Here is the image. This notify message appears to contain a file reference for each chunk of each file uploaded. The message was for an upload of 30 x 8MB files. The files look like they were broken into 1MB chunks on the client, and then uploaded to the server.

**Comment by AlexandreSajus** [comment]
Would you like to get on a call to discuss how we could help? We would like to understand your use case better. Send me an email at alexandre.sajus@avaiga.com with your availabilities

**Comment by FlorianJacta** [comment]
Hi @DeepSkyWonder, thank you for your incredible feedback.

I have created an issue for the first problem you encounter: https://github.com/Avaiga/taipy/issues/2126

Could you provide more information on the other two issues so I can create and fix them for you, such as a reproducible piece of code, environment info, use cases, etc.?

And, you can contact @AlexandreSajus too!

**Comment by DeepSkyWonder** [comment]
Hi Florian,

Thanks for creating an issue for the \<center\> tag, and suggesting a workaround. We suspected it would be something straight-forward like that.

We are still working through the other two problems. When we have a clearer idea of what is happening, we will extract the relevant bits of code and post an issue.

Our main issue is that the 'disable notify' fix is only available in 4.0, and we are working with 3.1.1 (4.0 breaks our app at the moment). 

As you can see from the attached screenshot (above) the notify box presents several problems in 3.1.1. (1) It ends, up becoming very large for multiple uploads, taking up the whole screen. (2) It lists each file multiple times. We think because it lists each file for each chunk received from the client. (3) We take the uploaded files, store them in amazon S3, and cache them locally using Cloudpathlib. We do not want to notify the user that the files are available, to use, until this process has completed.

I know this issue is currently closed. Would it be helpful if I open a new issue? Or is this the appropriate place to handle this?

Kind regards Cameron :-)

**Comment by DeepSkyWonder** [comment]
> Would you like to get on a call to discuss how we could help? We would like to understand your use case better. Send me an email at [alexandre.sajus@avaiga.com](mailto:alexandre.sajus@avaiga.com) with your availabilities

Thanks. I just sent through an email. Cameron :-)
