### ISSUE TITLE
Python 3.12 Support

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#627]
Taipy must support Python 3.12.

- [ ] Update the documentation
- [x] Update the GitHub templates
- [x] Update the GitHub actions.
- [x] Run tests
- [x] README files

**Comment by joaoandre-avaiga** [comment]
We need to make a techinical release (3.0.1?) to support python 3.12 due to a dependency on a old version of pyarrow.

To be able to install taipy on python 3.12, the user needs to:

- Upgrade pip to the latest version due to distutils being deprecated. `pip install --upgrade pip`
- Upgrade setuptools to the latest version. `pip install --upgrade setuptools`

For the taipy team, we need to:
 - Update pyarrow dependency to at least version 14.0
 - Release a technical release.

@jrobinAV @FabienLelaquais

**Comment by elia-bracci-hs** [comment]
@joaoandre-avaiga any update on this? 🙏

**Comment by jrobinAV** [comment]
> @joaoandre-avaiga any update on this? 🙏

@EliaBracciSumo The next version will support Python 3.12. We target a release for the end of February or the beginning of March. 

Meanwhile, you can try using the `develop` version of taipy (not stable) that supports Python 3.12.
