### ISSUE TITLE
Linters auto-complete Config and Gui to lowercase

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#708]
This feedback comes from a one-hour beta testing session of scenario management

taipy (the library) has both a Gui and a gui object. When typing `from taipy import Gui` and pressing Enter to go to the next line, linters will auto-complete by replacing `Gui` with `gui`
![image](https://github.com/Avaiga/taipy/assets/62465003/d31ff9bd-cbf9-4ccc-873f-54aa260f24e9)

This forces me to press Escape or to fix the case error after it happens which is frustrating. It can also lead to errors for new users

The same error is triggered with Config

**Comment by ooooo-create** [comment]
Hi,
I find this topic quite fascinating and would be most grateful if you could share more insights about the fundamental principles behind it within the context of a GitHub discussion.

**Comment by trgiangdo** [comment]
Hello @AlexandreSajus and @ooooo-create,

The `gui` and `Gui` are 2 different objects in Taipy package.
- `Gui` is the object that can be used to start the GUI service
- `gui` is a module, that from it you can import other Gui object, like `builder`, `page`, ...

The same argument can be pointed out for `Core` - `core`, `Config` - `config`.

I don't think there is anything we can do about it since we want `taipy-gui`, `taipy-core`, and `taipy-config` can be functional as independent packages.

**Comment by AlexandreSajus** [comment]
Yeah I'm also not sure how we could fix this outside of doing a lot of renaming. You can close as non-planned
