### ISSUE TITLE
Automatically generate config.pyi files

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#77]
Today config.pyi file is manually written in taipy-config repository.

This creates unwanted dependency of taipy-config on taipy-core. 

This pyi generation should be generalized to all repos having config sections 

Expected solution: 

- investigating potential existing solution
- Design a solution

**Comment by FredLL-Avaiga** [comment]
looks like mypy/stubgen got you covered ...
https://github.com/python/mypy/blob/master/mypy/stubgen.py

**Comment by joaoandre-avaiga** [comment]
That's not really the case @FredLL-Avaiga, because we have to generate a stub file from code that is injected in taipy-config at runtime, so I don't think this will quite suffice. Maybe we can try to adapt it somehow...

I have written a [poc](https://gist.github.com/joaoandre-avaiga/6e43cc11ca5d0f68b4ec68d7e4a0b2f1) as well that we can evaluate a worflow for it.
