### ISSUE TITLE
BUG-Module Python model is not sent via websocket

### ISSUE THREAD

**Issue by bengaid** [Avaiga/taipy#810]
Let this example : <https://github.com/bengaid/velib_taipy_chalkit>

Clone it to get it. Run it in the latest Taipy / Chalk'it setup.

At browser side, module `velib_real_time_page` variables does not exist : 

![image](https://github.com/Avaiga/taipy/assets/39761578/5c255d56-9521-41b4-b6d5-38c152a035ff)

Thus, it is not possible to perform bindings with Chalk'it variables.

**Comment by dinhlongviolin1** [comment]
I have looked at the code. Took me a while but the issue has nothing to do with Taipy but a problem with JSON decoding. The nan value of the dataframe get sent to the frontend as NaN. and since NaN is not valid JSON, the parsing is incorrect. I have updated the function to fill out the nan value of the heatmap data and everything is working fine now. I will push add more information on the websocket message so you can also debug it when needed.

The added line is the `heatmap_data = heatmap_data.fillna(0)` line
```
def generate_heatmap_data(geo_df):
    """
    Generate heatmap data from a GeoDataFrame.

    Args:
    - geo_df: A GeoDataFrame containing bike station data with latitude, longitude, and bikes availability rate.

    Returns:
    - A dictionary suitable for generating a heatmap on the JavaScript side, including the location and bikes availability rate.
    """
    # Extract relevant data for the heatmap
    heatmap_data = geo_df[['lat', 'lng', 'bikes_availability_rate']].copy()
    heatmap_data = heatmap_data.fillna(0)

    # Convert the DataFrame to a list of dictionaries for easy JSON serialization
    heatmap_data_list = heatmap_data.to_dict(orient='records')

    # Prepare the configuration for the heatmap display
    heatmap_config = {
        "data": heatmap_data_list,
        "config": {
            "opacity": 0.9,
            "radius": 80,
            "disableAutoscale": False,
            "min": 0,
            "max": 1,
            "colorScale": "interpolateRdYlBu",
            "reverseColorScale": False
        }
    }
    return heatmap_config
```
