### ISSUE TITLE
Ordering rules for creating config objects, followed by Scenarios, Tasks, Pipelines

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy#86]
I had a code working great with taipy 2.0.  When upgrading to version 2.1, it failed.  I discovered the following:

1. You have to create all the `Config` objects _before_ calling `Core.run()`
2. You have to create all of the `Scenario`, `Task` and `Pipeline` objects (and maybe others) _after_ calling `Core.run()`

I think this should be documented.  At least in the migration guide.

**Comment by jrobinAV** [comment]
Indeed, Core.run() is locking the configuration for updates. That must absolutely be documented.

By the way, the config can be unlocked manually after running Core(), and the config can be updated. But with great care, since this could make some old entities not compatible with the config changes.

We have another GitHub issue that is partly related to this.
