### ISSUE TITLE
Use setuptools instead of Distutils

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#97]
distutils will be removed in 3.12 planned for Q4 2023

**target release date**: October, 2nd 2023

**Migration path**: https://peps.python.org/pep-0632/#migration-advice

**Acceptance criteria**: Make sure taipy (and all other packages) are Python 3.12 compatible

**Comment by trgiangdo** [comment]
Hello @jrobinAV, where correctly are we using the `distutils` package?

**Comment by trgiangdo** [comment]
Hello @florian-vuillemot, is this issue still relevant?

**Comment by florian-vuillemot** [comment]
If I remember correctly we are not using distutil. But we have a problem because we have to use a `setup.py` file instead of a `setup.toml`. Perhaps we should create a new problem to improve our construction. In any case, it's not a priority.

**Comment by trgiangdo** [comment]
It is recommended by `setuptools` to add `[project]` field in the `pyproject.toml` file. `setup()` is still supported anyway: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

Either way, I believe this issue is obsolate. I will create a new issue on the TOML format and close this issue if it's ok.

**Comment by trgiangdo** [comment]
New issue https://github.com/Avaiga/taipy/issues/1286 is created on replacing the `setuptools.setup()`
